import { Toaster } from '@/components/ui/sonner'
import { GeistMono } from 'geist/font/mono'
import { GeistSans } from 'geist/font/sans'
import { Metadata } from 'next/types'
import { NuqsAdapter } from 'nuqs/adapters/next/app'

import '@/styles/globals.css'
import Script from 'next/script'

export const metadata: Metadata = {
  title: 'Nexulty › Elevate your IT-Support',
  description: 'Generated by create next app',
}

type Props = {
  children: React.ReactNode
}

export default function RootLayout({ children }: Props) {
  return (
    <html
      lang='en'
      suppressHydrationWarning
      className={`${GeistSans.variable} ${GeistMono.variable}`}
    >
      <body className='antialiased'>
        {process.env.NODE_ENV === 'production' && (
          <Script
            defer
            src='https://analytics.strmrlab.de/script.js'
            data-website-id='74586d46-3019-4962-8a0e-9aa453756f07'
          />
        )}
        <main className='h-screen w-screen'>
          <NuqsAdapter>{children}</NuqsAdapter>
        </main>
        <Toaster />
      </body>
    </html>
  )
}
